eTickets/Controllers/ActorsController.cs
using eTickets.Data.Services.Interfaces;
using eTickets.Models;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace eTickets.Controllers
{
    public class ActorsController : Controller
    {
        private readonly IActorsService _service;

        public ActorsController(IActorsService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAllAsync();
            return View(data);
        }

        // Get: Actors/Create
        public IActionResult Create()
        {
            return View();
        }

        // Post: Actors/Create
        [HttpPost]
        public async Task<IActionResult> Create([Bind("FullName", "ProfilePictureURL" ,"Bio")]Actor actor)
        {
            if (!ModelState.IsValid)
            {
                return View(actor);
            }
            await _service.AddAsync(actor);
            return RedirectToAction(nameof(Index));
        }

        // Get: Actors/Details/Id
        public async Task<IActionResult> Details(int Id)
        {
            var ActorDetails = await _service.GetByIdAsync(Id);
            if (ActorDetails == null) return View("NotFound");
            return View(ActorDetails);
        }

        // Get: Actors/Edit/Id
        public async Task<IActionResult> Edit(int Id)
        {
            var ActorDetails = await _service.GetByIdAsync(Id);
            if (ActorDetails == null) return View("NotFound");
            return View(ActorDetails);
        }

        // Post: Actors/Edit
        [HttpPost]
        public async Task<IActionResult> Edit(int Id, [Bind("Id", "FullName", "ProfilePictureURL", "Bio")] Actor actor)
        {
            if (!ModelState.IsValid)
            {
                return View(actor);
            }
            await _service.UpdateAsync(Id, actor);
            return RedirectToAction(nameof(Index));
        }

        // Get: Actors/Delete/Id
        public async Task<IActionResult> Delete(int Id)
        {
            var ActorDetails = await _service.GetByIdAsync(Id);
            if (ActorDetails == null) return View("NotFound");
            return View(ActorDetails);
        }

        // Post: Actors/Delete
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmation(int Id)
        {
            var ActorDetails = await _service.GetByIdAsync(Id);
            if (ActorDetails == null) return View("NotFound");

            await _service.DeleteAsync(Id);
            return RedirectToAction(nameof(Index));
        }
    }
}

eTickets/Controllers/CinemasController.cs
using eTickets.Data.Services.Interfaces;
using eTickets.Models;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace eTickets.Controllers
{
    public class CinemasController : Controller
    {
        private readonly ICinemasService _service;

        public CinemasController(ICinemasService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAllAsync();
            return View(data);
        }

        // Get: Cinemas/Create
        public IActionResult Create()
        {
            return View();
        }

        // Post: Cinemas/Create
        [HttpPost]
        public async Task<IActionResult> Create([Bind("Name", "Logo", "Description")] Cinema cinema)
        {
            if (!ModelState.IsValid)
            {
                return View(cinema);
            }
            await _service.AddAsync(cinema);
            return RedirectToAction(nameof(Index));
        }

        // Get: Cinemas/Details/Id
        public async Task<IActionResult> Details(int Id)
        {
            var cinemaDetails = await _service.GetByIdAsync(Id);
            if (cinemaDetails == null) return View("NotFound");
            return View(cinemaDetails);
        }

        // Get: Cinemas/Edit/Id
        public async Task<IActionResult> Edit(int Id)
        {
            var cinemaDetails = await _service.GetByIdAsync(Id);
            if (cinemaDetails == null) return View("NotFound");
            return View(cinemaDetails);
        }

        // Post: Cinemas/Edit
        [HttpPost]
        public async Task<IActionResult> Edit(int Id, [Bind("Id", "Name", "Logo", "Description")] Cinema cinema)
        {
            if (!ModelState.IsValid) return View(cinema);

            if(Id == cinema.Id)
            {
                await _service.UpdateAsync(Id, cinema);
                return RedirectToAction(nameof(Index));
            }
            return View(cinema);
        }

        // Get: Cinemas/Delete/Id
        public async Task<IActionResult> Delete(int Id)
        {
            var cinemaDetails = await _service.GetByIdAsync(Id);
            if (cinemaDetails == null) return View("NotFound");
            return View(cinemaDetails);
        }

        // Post: Cinemas/Delete
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmation(int Id)
        {
            var cinemaDetails = await _service.GetByIdAsync(Id);
            if (cinemaDetails == null) return View("NotFound");

            await _service.DeleteAsync(Id);
            return RedirectToAction(nameof(Index));
        }
    }
}

eTickets/Controllers/MoviesController.cs
using eTickets.Data.Services.Interfaces;
using eTickets.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;
using System.Threading.Tasks;

namespace eTickets.Controllers
{
    public class MoviesController : Controller
    {
        private readonly IMoviesService _service;

        public MoviesController(IMoviesService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAllAsync(n => n.Cinema);
            return View(data);
        }

        // Get: Movies/Filter
        public async Task<IActionResult> Filter(string searchString)
        {
            var data = await _service.GetAllAsync(n => n.Cinema);
            if(!string.IsNullOrEmpty(searchString))
            {
                var filteredMovies = data.Where(n => n.Name.Contains(searchString) || n.Description.Contains(searchString)).ToList();
                return View("Index", filteredMovies);
            }
            return View("Index", data);
        }

        // Get: Movies/Create
        public async Task<IActionResult> Create()
        {
            var dropdownValues = await _service.GetNewMovieDropDownsValues();
            ViewBag.Cinemas = new SelectList(dropdownValues.Cinemas, "Id", "Name");
            ViewBag.Actors = new SelectList(dropdownValues.Actors, "Id", "FullName");
            ViewBag.Producers = new SelectList(dropdownValues.Producers, "Id", "FullName");
            return View();
        }

        // Post: Movies/Create
        [HttpPost]
        public async Task<IActionResult> Create(NewMovieVM movie)
        {
            if (!ModelState.IsValid)
            {
                var dropdownValues = await _service.GetNewMovieDropDownsValues();
                ViewBag.Cinemas = new SelectList(dropdownValues.Cinemas, "Id", "Name");
                ViewBag.Actors = new SelectList(dropdownValues.Actors, "Id", "FullName");
                ViewBag.Producers = new SelectList(dropdownValues.Producers, "Id", "FullName");
                return View(movie);
            }
            await _service.AddNewMovieAsync(movie);
            return RedirectToAction(nameof(Index));
        }

        // Get: Movies/Details/Id
        public async Task<IActionResult> Details(int Id)
        {
            var MovieDetails = await _service.GetMovieByIdAsync(Id);
            if (MovieDetails == null) return View("NotFound");
            return View(MovieDetails);
        }

        // Get: Movies/Edit/Id
        public async Task<IActionResult> Edit(int Id)
        {
            var MovieDetails = await _service.GetMovieByIdAsync(Id);
            if (MovieDetails == null) return View("NotFound");

            var response = new NewMovieVM()
            {
                Id = MovieDetails.Id,
                Name = MovieDetails.Name,
                Description = MovieDetails.Description,
                Price = MovieDetails.Price,
                ImageURL = MovieDetails.ImageURL,
                StartDate = MovieDetails.StartDate,
                EndDate = MovieDetails.EndDate,
                MovieCategory = MovieDetails.MovieCategory,
                CinemaId = MovieDetails.CinemaId,
                ProducerId = MovieDetails.ProducerId,
                ActorIds = MovieDetails.Actors_Movies.Select(n => n.ActorId).ToList()
            };

            var dropdownValues = await _service.GetNewMovieDropDownsValues();
            ViewBag.Cinemas = new SelectList(dropdownValues.Cinemas, "Id", "Name");
            ViewBag.Actors = new SelectList(dropdownValues.Actors, "Id", "FullName");
            ViewBag.Producers = new SelectList(dropdownValues.Producers, "Id", "FullName");

            return View(response);
        }

        // Post: Movies/Edit
        [HttpPost]
        public async Task<IActionResult> Edit(int Id, NewMovieVM movie)
        {
            if (Id != movie.Id) return View("NotFound");

            if (!ModelState.IsValid)
            {
                var dropdownValues = await _service.GetNewMovieDropDownsValues();
                ViewBag.Cinemas = new SelectList(dropdownValues.Cinemas, "Id", "Name");
                ViewBag.Actors = new SelectList(dropdownValues.Actors, "Id", "FullName");
                ViewBag.Producers = new SelectList(dropdownValues.Producers, "Id", "FullName");
                return View(movie);
            }
            await _service.UpdateMovieAsync(movie);
            return RedirectToAction(nameof(Index));
        }

        // Get: Movies/Delete/Id
        public async Task<IActionResult> Delete(int Id)
        {
            var MovieDetails = await _service.GetByIdAsync(Id);
            if (MovieDetails == null) return View("NotFound");
            return View(MovieDetails);
        }

        // Post: Movies/Delete
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmation(int Id)
        {
            var MovieDetails = await _service.GetByIdAsync(Id);
            if (MovieDetails == null) return View("NotFound");

            await _service.DeleteAsync(Id);
            return RedirectToAction(nameof(Index));
        }
    }
}

eTickets/Controllers/OrdersController.cs
using eTickets.Data.Cart;
using eTickets.Data.Services.Interfaces;
using eTickets.Data.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eTickets.Controllers
{
    public class OrdersController : Controller
    {
        public readonly ShoppingCart _shoppingCart;
        public readonly IMoviesService _moviesService;
        public readonly IOrdersService _ordersService;
        public OrdersController(IMoviesService moviesService, ShoppingCart shoppingCart, IOrdersService ordersService)
        {
            _shoppingCart = shoppingCart;
            _moviesService = moviesService;
            _ordersService = ordersService;
        }

        public IActionResult ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var response = new ShoppingCartVM()
            {
                shoppingCart = _shoppingCart,
                ShoopingCartTotal = _shoppingCart.GetShoppingCartTotal
            };

            return View(response);
        }

        public async Task<RedirectToActionResult> AddItemToShoppingCart(int id)
        {
            var item = await _moviesService.GetMovieByIdAsync(id);
            if (item != null)
            {
                _shoppingCart.AddItemToCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<RedirectToActionResult> RemoveItemToShoppingCart(int id)
        {
            var item = await _moviesService.GetMovieByIdAsync(id);
            if (item != null)
            {
                _shoppingCart.RemoveItemfromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            var userId = "";
            var userEmail = "";

            await _ordersService.StoreOrderAsync(items, userId, userEmail);
            await _shoppingCart.ClearShoppingCartAsync();

            return View("OrdersCompleted");
        }

        public async Task<IActionResult> Index()
        {
            var userId = "";
            var orders = await _ordersService.GetOrdersByUserIdAsync(userId);

            return View(orders);
        }
    }
}

eTickets/Views/Shared/NotFound.cshtml
<div class="row">
    <div class="col-md-6 offset-3">
        <h1>You've reached the end of Internet</h1>
        <hr />
        <a class="btn btn-outline-success" asp-controller="Movies" asp-action="Index">Home Page</a>
    </div>
</div>

eTickets/Views/Shared/_CreateItem.cshtml
@model string

<div style="position: fixed; right: 25px; bottom: 25px;" class="text-white">
    <a asp-controller="@Model" asp-action="Create" class="btn btn-success">
    <i class="bi bi-plus-circle"></i> Add New</a>
</div>

eTickets/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - eTickets</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Movies" asp-action="Index">eTickets</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Movies" asp-action="Index"><i class="badge-info bi-film"></i>Movies</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" area-haspopup="true" area-expanded="false">
                                <i class="bi-film bi-gear"></i> Management
                            </a>
                            <div class="dropdown-menu" area-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-controller="Cinemas" asp-action="Index"><i class="bi-film bi-camera-reels"></i>Cinemas</a>
                                <a class="dropdown-item" asp-controller="Actors" asp-action="Index"><i class="bi-film bi-person-square"></i>Actors</a>
                                <a class="dropdown-item" asp-controller="Producers" asp-action="Index"><i class="bi-film bi-headset"></i>Producers</a>
                            </div>
                        </li>
                    </ul>

                    <form class="form-inline my-2 my-lg-0" asp-controller="Movies" asp-action="Filter" style="padding-right: 25px;">
                        <input name="searchString" type="text" class="form-control" placeholder="Search for a movie..." aria-label="Recipient's username" aria-describedby="button-addon2">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                    </form>
                    <ul class="navbar nav">
                        @await Component.InvokeAsync("ShoppingCartSummary") 
                    </ul>

                    <div class="dropdown">
                        <button class="btn btn-outline-success dropdown-toggle" type="button" id="profile-btn" data-toggle="dropdown" area-expanded="false">
                            <i class="bi bi-person-badge"></i> Hello, User
                        </button>
                        <ul class="dropdown-menu" area-labelledby="profile-btn">
                            <li>
                                <a class="dropdown-item" asp-controller="Orders">
                                    <i class="bi bi-list"></i> Orders
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - eTickets
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>